spring:
  application:
    name: team-task-manager
  datasource:
    url: jdbc:mysql://${MYSQLHOST:mysql.railway.internal}:${MYSQLPORT:3306}/${MYSQLDATABASE:railway}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:QMUelClvabHvnMrmWDujxMDDHLHrkuVS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
