spring:
  application:
    name: team-task-manager
  datasource:
    url: jdbc:${MYSQL_URL:mysql://junction.proxy.rlwy.net:45952/railway}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:faDKdjUpbhZJLlrYQfVLLlXAEQlmwmJO}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
